# Generated by Django 3.2.13 on 2023-02-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('game_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.gamedate')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('game_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.gamedate')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('game_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.gamedate')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.sector')),
            ],
        ),
    ]
