# Generated by Django 3.2.13 on 2023-02-23 12:01

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_at',
            field=models.DateTimeField(default=auction.models.get_default_end_at),
        ),
    ]
