# Generated by Django 3.2.13 on 2023-02-22 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_auctionitem_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 12, 10, 8, 639039, tzinfo=utc)),
        ),
    ]
