# Generated by Django 3.2.13 on 2023-02-23 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_auctionitem_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 12, 30, 14, 27236, tzinfo=utc)),
        ),
    ]
