# Generated by Django 3.2.13 on 2023-02-26 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('items', '0001_initial'),
        ('assets', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_positions',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.gamedate'),
        ),
        migrations.AddField(
            model_name='user_positions',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.sector'),
        ),
        migrations.AddField(
            model_name='user_positions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_news',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.news'),
        ),
        migrations.AddField(
            model_name='user_news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='user_items',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='days',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.gamedate'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_accounts_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_accounts_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='inventory',
            field=models.ManyToManyField(through='accounts.User_Items', to='items.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ManyToManyField(through='accounts.User_Positions', to='assets.Sector'),
        ),
        migrations.AddField(
            model_name='user',
            name='read_news',
            field=models.ManyToManyField(through='accounts.User_News', to='assets.News'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
