# Generated by Django 3.2.13 on 2023-02-19 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230219_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_accounts_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
